name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

env:
  IMAGE: streamlit-app
  TAG: v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push (linux/amd64)
        run: |
          IMAGE_URI=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.AR_REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker buildx create --use || true
          docker buildx build --platform linux/amd64 -t $IMAGE_URI --push .

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.AR_REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image $IMAGE_URI \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --quiet

